version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "coinbase-ticker"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-qaou3cfvt0qi"
s3_prefix = "coinbase-ticker"
region = "us-east-1"
profile = "coinbase"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
